Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
  Reservations = [
    {
      _id: 1,
      USER: "User1",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "11",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 2,
      USER: "User1",
      VEHICLE: "vehicleType1",
      LOCATION: "LocationType1",
      RENTAL_DURATION: "12",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 1100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 3,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 4,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "33",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 5,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "6",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
    {
      _id: 6,
      USER: "User",
      VEHICLE: "vehicleType",
      LOCATION: "LocationType",
      RENTAL_DURATION: "23",
      PICKUP_TIME: "DateTypePickup",
      RETURN_TIME: "DateTypeReturn",
      PRICE: 100,
      USER_COMMENTS: "comments",
    },
  ];
  
  // export default Reservations;
                  